### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by YuvRaj6392** [AMAI-GmbH/AI-Expert-Roadmap#32]
Tyro at github
So creating an issue for learning purpose

**Comment by UsegDiazGranados** [comment]
My apologies; I'm new to this environment and have no issues whatsoever.

Although I'm up on most of the things that you put up on your flowchart
(not claiming to be an expert in all of them); I find your resource
incredibly helpful for strategic reasons.

Please let me know if there's something I need to do in order to correct
any eventual inconvenience created by my ignorance.


Sincerely,

Useg
...... ...... ......

Den sön 14 feb. 2021 16:01YuvRaj6392 <notifications@github.com> skrev:

**Comment by russparker37** [comment]
Nice
